# Generated by Django 5.0.7 on 2024-08-13 14:45

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('vk', models.CharField(max_length=100)),
                ('tg', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^@.+')])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('university', models.CharField(max_length=300)),
                ('faculty', models.CharField(max_length=300)),
                ('transfer', models.CharField(choices=[('OD', 'Да, от Одинцово и обратно'), ('PP', 'Да, от Парка Победы и обратно'), ('NO', 'Не нужен')], default='NO', max_length=2)),
                ('course', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('health_features', models.TextField(blank=True)),
            ],
        ),
    ]
