# Generated by Django 5.0.7 on 2024-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('vk', models.URLField(blank=True)),
                ('tg', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('university', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=10)),
                ('transfer', models.BooleanField(default=False)),
                ('health_features', models.TextField(blank=True)),
            ],
        ),
    ]
