# Generated by Django 5.0.7 on 2024-08-12 13:41

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('vk', models.CharField(max_length=100)),
                ('tg', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^@.+')])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('university', models.CharField(max_length=300)),
                ('op', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=100)),
                ('transfer', models.CharField(max_length=100)),
                ('health_features', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
